# Generated by Django 5.2.7 on 2026-08-16 10:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0003_crimerecord_admin_remark_crimerecord_proof_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(help_text='E.g. PCR Unit 03, Khargone Sector Alpha', max_length=100)),
                ('assigned_area', models.CharField(help_text='Patrol sector or hotspot', max_length=200)),
                ('shift', models.CharField(choices=[('morning', 'Morning Shift (06:00 - 14:00)'), ('evening', 'Evening Shift (14:00 - 22:00)'), ('night', 'Night Shift (22:00 - 06:00)')], default='night', max_length=20)),
                ('patrol_date', models.DateField(default=django.utils.timezone.now)),
                ('officer_in_charge', models.CharField(max_length=150)),
                ('contact_number', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active on Patrol'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-patrol_date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='crimerecord',
            options={'ordering': ['-incident_datetime', '-date_time']},
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='fir_number',
            field=models.CharField(blank=True, help_text='Official Police FIR / Case Tracking Number', max_length=40),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='incident_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Actual date and time when the crime occurred'),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='investigating_officer',
            field=models.CharField(blank=True, default='', help_text='Assigned IO / Detective name', max_length=150),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='landmark',
            field=models.CharField(blank=True, default='', help_text='Nearest identifiable landmark', max_length=255),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='police_station',
            field=models.CharField(blank=True, default='Khargone City Police Station', help_text='Jurisdiction police station handling this FIR', max_length=150),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='severity_level',
            field=models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='victim_age_group',
            field=models.CharField(blank=True, choices=[('juvenile', 'Under 18 (Juvenile)'), ('young_adult', '18 - 29 years'), ('adult', '30 - 50 years'), ('senior', 'Above 50 years'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='victim_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('undisclosed', 'Prefer not to say')], default='undisclosed', max_length=20),
        ),
        migrations.AddField(
            model_name='crimerecord',
            name='weapon_involved',
            field=models.CharField(blank=True, default='None', help_text='E.g. Firearm, Knife, Blunt Instrument, None', max_length=100),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='admin_remark',
            field=models.TextField(blank=True, help_text='Internal police / admin case notes', null=True),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='crime_type',
            field=models.CharField(choices=[('theft', 'Theft'), ('assault', 'Assault'), ('robbery', 'Robbery'), ('murder', 'Murder'), ('fraud', 'Fraud & Cybercrime'), ('vandalism', 'Vandalism'), ('drug_offense', 'Drug Offense'), ('burglary', 'Burglary & Break-in'), ('harassment', 'Harassment & Stalking'), ('vehicle_theft', 'Vehicle Theft'), ('other', 'Other Incident')], default='theft', max_length=30),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='description',
            field=models.TextField(help_text='Detailed narrative of the incident'),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='location_name',
            field=models.CharField(blank=True, help_text='Area, street name, or landmark', max_length=255),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='proof_file',
            field=models.FileField(blank=True, help_text='Supporting evidence, FIR photo, or complaint PDF', null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_crimes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crimerecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Verified & Registered'), ('investigating', 'Under Active Investigation'), ('resolved', 'Case Solved / Closed'), ('rejected', 'Rejected / Invalid')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CrimeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alert_type', models.CharField(choices=[('warning', 'Security Warning'), ('high_risk', 'High-Risk Hotspot Advisory'), ('patrol', 'Patrol Dispatch Notice'), ('emergency', 'Emergency Broadcast')], default='warning', max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('warning', 'Moderate Warning'), ('danger', 'Critical Danger')], default='warning', max_length=20)),
                ('message', models.TextField()),
                ('location_name', models.CharField(blank=True, help_text='Target zone or neighborhood', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('query_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('predicted_crime_type', models.CharField(max_length=50)),
                ('predicted_severity', models.CharField(max_length=20)),
                ('risk_score', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queried_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
