# Generated by Django 5.2.7 on 2026-08-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Count of consecutive incorrect attempts'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='signup_payload',
            field=models.JSONField(default=dict, help_text='Serialized user registration data'),
        ),
    ]
